/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "test-java-project"
pluginManagement {
    repositories {
        maven {
            url = uri("plugin-gradle/repo")
        }
    }
}
